### PR TITLE
Neighbor highlighting via mouseover and click at the same time 

### PR DESCRIPTION
**Pull request by sgrubsmyon**
This change is a bit more complicated. It enables using both neighbor highlighting on click and neighbor highlighting on mouse over at the same time. Both modes can exist simultaneously.

The diff looks larger than necessary because the indentation was a bit messy and I tried to fit the changes in without indentation jump. I did not manage to get it right, but I think some of the indentation in the file is already mixing tabs and spaces anyway in an unpredictable manner. Feel free to unify code indentation globally.

Cheers!

### CODE REVIEW

**Comment by JohnCoene** [comment]
Hi Markus!

Thanks for another great PR. Could this accidentally fix https://github.com/JohnCoene/sigmajs/issues/8? Yes, the indentation was messy to say the least...

I haven't taken care of sigmajs as much as I should have over the years, I have pushed few commits, not released on CRAN, etc. I can tell by the quality of the PRs that you care about the project and probably understand sigma.js more than I do now: would you like to be the maintainer of the package? 

I would give you access to the repository so you can push directly (no PR required) and you would go from contributor (`ctb`) to author (`aut`) in the `DESCRIPTION`.

Please don't feel obliged to say yes. Let me know if that could interest you.

**Comment by sgrubsmyon** [comment]
Hi John,

I don't know if I want to be maintainer of sigmajs. I probably could. I simply try to use it in ways appropriate for my work and modify it accordingly. If that's enough for now to be maintainer, then I can do it. I can probably also look at some small issues now and then. The issue tracker does not look too crowded, fortunately.

I think I do not know it as well as you do yet. But probably you also lose knowledge of it with every day you do not have time to look at it.

So, I think I can agree to be a maintainer of sigmajs.

**Comment by sgrubsmyon** [comment]
Btw, I cannot imagine this to be in any way related to #8. I have not touched on any crosstalk stuff. But who knows... I have seen that the SelectionHandle (`sel_handle`) in the part of code I modified has to do with crosstalk. But I didn't change anything about it.

**Comment by JohnCoene** [comment]
Great!

Don't worry, it's no strings attached :) I'll add you to the repo, feel free to add yourself as author.

**Comment by sgrubsmyon** [comment]
Done.

**Pull request merged**
